server:
  port: 7070
  tomcat:
    connection-timeout: 4s
    keep-alive-timeout: 20s
    threads:
      max: 100
      min-spare: 10
spring:
  application:
    name: cloud-config-test-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hoon512/cloud-config-test-config-repo.git
          default-label: main

